### ISSUE TITLE
Updating roles fails with error message: Could not create role

### ISSUE THREAD

**Issue by mreiche** [stevehipwell/helm-charts#1059]
Roles are not updated in ConfigJob.

Steps to reproduce:

1. Create a new repository
2. Create roles with repository privileges
3. Create users

## First run

```yaml
config:
  enabled: true
  repos:
    - name: osm-maps
      format: raw
      type: hosted
      online: true
      storage:
        blobStoreName: default
        strictContentTypeValidation: false
        writePolicy: allow

  roles:
    - id: osm-writer
      name: osm-writer
      privileges:
        - nx-repository-view-raw-osm-maps-*
    - id: osm-reader
      name: osm-reader
      privileges:
        - nx-repository-view-raw-osm-maps-read
  users:
    - userId: osm-writer
      firstName: OSM
      lastName: Writer
      emailAddress: "osm-writer@{{ fqdn }}"
      status: active
      roles:
        - osm-writer
    - userId: osm-reader
      firstName: OSM
      lastName: Reader
      emailAddress: "osm-reader@{{ fqdn }}"
      status: active
      roles:
        - osm-reader
```

Config Job
```
Configuring Nexus3...
Waiting for Nexus...
Waiting for Nexus...
Waiting for Nexus...
Waiting for Nexus...
Configuring anonymous access...
Anonymous access configured.
Configuring roles...
Role 'nx-metrics' configured.
ERROR: Could not create role 'osm-reader'.
```

Probaby role created before repository.

## Second run
```yaml
  roles:
    - id: osm-writer
      name: osm-writer
#      privileges:
#        - nx-repository-view-raw-osm-maps-*
    - id: osm-reader
      name: osm-reader
#      privileges:
#        - nx-repository-view-raw-osm-maps-read
```

Config Job
```
Configuring Nexus3...
Configuring anonymous access...
Anonymous access configured.
Configuring roles...
Role 'nx-metrics' configured.
Role 'osm-reader' configured.
Role 'osm-writer' configured.
Configuring users...
User 'osm-reader' configured.
User 'osm-writer' configured.
Configuring blob stores...
Configuring scripts...
Script 'cleanup' updated.
Script 'task' updated.
Configuring cleanup policies...
Configuring repositories...
Repository 'osm-maps' configured.
Configuring tasks...
Nexus3 configured successfully!
```

## Third run
```yaml
  roles:
    - id: osm-writer
      name: osm-writer
      privileges:
        - nx-repository-view-raw-osm-maps-*
    - id: osm-reader
      name: osm-reader
      privileges:
        - nx-repository-view-raw-osm-maps-read
```

Config Job
```
Configuring Nexus3...
Configuring anonymous access...
Anonymous access configured.
Configuring roles...
Role 'nx-metrics' configured.
ERROR: Could not create role 'osm-reader'.
```

**Comment by mreiche** [comment]
This bug is back:
```yaml
roles:
    - id: oci-reader
      name: oci-reader
      privileges:
        - nx-repository-view-docker-oci-read
        - nx-repository-view-docker-oci-browse
```
```
Configuring Nexus3...
Configuring anonymous access...
Anonymous access configured.
Configuring blob stores...
Configuring scripts...
Script 'cleanup' updated.
Script 'task' updated.
Configuring cleanup policies...
Configuring repositories...
Repository 'oci' configured.
Configuring roles...
Role 'nx-metrics' configured.
ERROR: Could not create role 'oci-reader'.
Stream closed EOF for nexus/nexus-nexus3-config-26-dwfsf (config)
```
