### ISSUE TITLE
Applying nexus 5.1.0 (from 5.0.0) leads to a deployment issues

### ISSUE THREAD

**Issue by EugenMayer** [stevehipwell/helm-charts#1063]
Going from 5.0.0 to 5.1.0 i get this error

```
cannot patch "nexus" with kind StatefulSet: StatefulSet.apps "nexus" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'ordinals', 'template', 'updateStrategy', 'persistentVolumeClaimRetentionPolicy' and 'minReadySeconds' are forbidden
```

with this configuration. 
```yaml
image:
  tag: ${tag}

properties:
- nexus.skipDefaultRepositories=true
- nexus.scripts.allowCreation=false
- nexus.clustered=false
- nexus.loadAsOSS=true
- nexus.orient.enabled=false
- nexus.datastore.enabled=true

config:
  enabled: false

fullnameOverride: ${nexus_name}
nameOverride: ${nexus_name}

serviceAccount:
  create: false

persistence:
  enabled: true
  size: ${storage_size}Gi
  storageClass: "local-path"

service:
  enabled: true
  name: ${nexus_name}

install4jAddVmParams: "-XX:MaxDirectMemorySize=2048m -Xms2000m -Xmx6000m"

env:
  - name: NEXUS_SECURITY_RANDOMPASSWORD
    value: "false"

plugins:
  - name: nexus-repository-composer
    url: https://search.maven.org/remotecontent?filepath=org/sonatype/nexus/plugins/nexus-repository-composer/0.1.5/nexus-repository-composer-0.1.5-bundle.kar

podSecurityContext:
  fsGroup: 200

securityContext:
  runAsGroup: 200
  runAsUser: 200
  fsGroupChangePolicy: "OnRootMismatch"

licence:
  enabled: false
```

Misc:
- i did not change the configuration in any way (deploying helm charts via terraform, so that can be told quiet for sure)
- running k8s 1.30.5
