### ISSUE TITLE
Docker not work with Nexus 

### ISSUE THREAD

**Issue by williank** [stevehipwell/helm-charts#1068]
Hello friends.. I'm not able to configure Nexus to work with Docker, this is my values.yaml

(trec) ➜  trec git:(adjust/tasks/models) ✗ docker login registry.mydomain.digital
Username: 123
Password: 
Error response from daemon: login attempt to https://registry.mydomain.digital/v2/ failed with status: 404 Not Found

```
service:
  type: ClusterIP
  clusterIP:
  annotations: {}
  port: 8081
  additionalPorts:
    - port: 8082
      name: docker-group
      containerPort: 8082
      hosts:
        - nexus-loca.local
    - port: 8083
      name: docker-hosted
      containerPort: 8083
      hosts:
        - registry.mydonain.digital

ingress:
  enabled: true
  ingressClassName: "traefik"
  annotations:
    traefik.ingress.kubernetes.io/redirect-entry-point: "https"  # Redireciona HTTP para HTTPS
    traefik.ingress.kubernetes.io/router.entrypoints: "websecure"  # Define o entrypoint como HTTPS
    traefik.ingress.kubernetes.io/router.tls: "true"  # Habilita TLS no Traefik
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - nexus.mydonain.digital  # Nome de domínio em minúsculas
    - registry.mydonain.digital
  paths:
    - path: /  # Caminho
      pathType: Prefix  # Adicionando o pathType
  tls:
    - secretName: nexus-tls-secret  # Nome do Secret que contém o certificado TLS
      hosts:
        - nexus.mydonain.digital  # Nome de domínio em minúsculas
        - registry.mydonain.digital
  servicePort: 8081
```
