### ISSUE TITLE
[nexus3] configuring users fails in v5.6.0

### ISSUE THREAD

**Issue by dmitry-mightydevops** [stevehipwell/helm-charts#1115]
**I am unable to provision users with a fresh install of the HELM chart**

```sh
helm upgrade --install nexus oci://ghcr.io/stevehipwell/helm-charts/nexus3 --version 5.6.0 --values tests/nexus/values.yaml
```

```sh
➜  klo nexus-config-1-mpd26
Configuring Nexus3...
Waiting for Nexus...
Configuring anonymous access...
Anonymous access configured.
Configuring blob stores...
Configuring scripts...
Script 'cleanup' updated.
Script 'task' updated.
Configuring cleanup policies...
Configuring repositories...
Configuring roles...
Role 'nx-metrics' configured.
Configuring users...
jq: error: syntax error, unexpected end of file, expecting QQSTRING_TEXT or QQSTRING_INTERP_START or QQSTRING_END (Unix shell quoting issues?) at <top-level>, line 1:
.source // "default
jq: 1 compile error
```

## values.yaml

```yaml
fullnameOverride: nexus

serviceAccount:
  create: true
  annotations: {}

ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-staging
    nginx.ingress.kubernetes.io/proxy-body-size: 100m
    nginx.ingress.kubernetes.io/server-snippet: add_header X-Robots-Tag "noindex, nofollow, nosnippet, noarchive";
    nginx.ingress.kubernetes.io/use-regex: "true"
  ingressClassName: nginx
  hosts:
    - nexus.domain.com
  tls:
    - hosts:
        - nexus.domain.com
      secretName: nexus.domain.com-crt

replicas: 1

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  storageClass: gp3
  size: 32Gi
  retainDeleted: false
  retainScaled: false

resources: {}
# We usually recommend not to specify default resources and to leave this as a conscious
# choice for the user. This also increases chances charts run on environments with little
# resources, such as Minikube. If you do want to specify resources, uncomment the following
# lines, adjust them as necessary, and remove the curly braces after 'resources:'.
#   limits:
#     cpu: 100m
#     memory: 128Mi
#   requests:
#     cpu: 100m
#     memory: 128Mi

nodeSelector:
  ops: "true"

affinity: {}
topologySpreadConstraints: []
tolerations: []

metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    interval: 30s
    scrapeTimeout: 25s
    additionalLabels:
      release: prometheus

rootPassword:
  secret: nexus-credentials
  key: admin-password

config:
  enabled: true
  job:
    nodeSelector:
      ops: "true"
    affinity: {}
    tolerations: []
  anonymous:
    enabled: false
  users:
    - userId: "tekton"
      firstName: "Tekton"
      lastName: "Build Bot"
      emailAddress: "no-reply@domain.com"
      source: "default"
      status: "active"
      roles:
        - "nx-admin"
      password:
        secret: "nexus-credentials"
        key: "tekton-password"

```

## nexus-credentials

Contains credentials for users I want to provision (tekton/tekton-password)

```sh
➜ kgsecn nexus nexus-credentials -o go-template='{{range $k,$v := .data}}{{printf "%s: " $k}}{{if not $v}}{{$v}}{{else}}{{$v | base64decode}}{{end}}{{"\n"}}{{end}}'
admin-password: xxx
developer-password: yyy
tekton-password: zzz
```
