### ISSUE TITLE
specifying repos credentials fails the job

### ISSUE THREAD

**Issue by dmitry-mightydevops** [stevehipwell/helm-charts#1162]
job fails with:

```sh
✗  klo nexus-config-1-ndx2g
Configuring Nexus3...
Configuring anonymous access...
Anonymous access configured.
Configuring blob stores...
Configuring scripts...
Script 'cleanup' updated.
Script 'task' updated.
Configuring cleanup policies...
Configuring repositories...
ERROR: Could not create repository 'pypi-proxy'.
```

the helm config for repos:

```sh
      repos:
        - name: pypi-proxy
          format: pypi
          type: proxy
          url: https://pypi.org/
          online: true
          storage:
            blobStoreName: default
            strictContentTypeValidation: true
            writePolicy: allow
          proxy:
            remoteUrl: https://pypi.org/
            metadataMaxAge: 10080 # Metadata cache TTL (minutes) - 7 days
            contentMaxAge: 43200  # Content cache TTL (minutes)  - 30 days
          negativeCache:
            enabled: true
            timeToLive: 10080
          httpClient:
            blocked: false       # Do not block outbound requests
            autoBlock: true      # Auto-block if remote is unreachable
            retries: 1           # No retry on remote fetch failures
            useTrustStore: false # Don't use custom trust store for SSL
          password:
            secret: pip-credentials
            key: tekton-password
```

the password exists in the same namespace

```sh
➜ kgsecn nexus pip-credentials -o go-template='{{range $k,$v := .data}}{{printf "%s: " $k}}{{if not $v}}{{$v}}{{else}}{{$v | base64decode}}{{end}}{{"\n"}}{{end}}'
tekton-password: FNXaY4FyTYSXPmyY
```

**Comment by stevehipwell** [comment]
@dmitry-mightydevops what does your job config YAML look like?

**Comment by stevehipwell** [comment]
@dmitry-mightydevops just checking you saw my reply?

**Comment by dmitry-mightydevops** [comment]
Yes, will reply tomorrow

**Comment by stevehipwell** [comment]
@dmitry-mightydevops you've not replied. Is this issue still valid or would you like me to close if for you?

**Comment by sule26** [comment]
Hi @stevehipwell, I'm facing the same issue and was wondering if you could help.

Every time I update users or repositories, I get an error message. Initially, I created a Dev user when deploying the application for the first time. Now, I'm trying to add a user for each team in my company.

The problem is that the process successfully creates users at the top of the list, but fails when it reaches the Dev user. As a result, the remaining users aren’t created. I also tried forcing the job to run again, but now it fails on the first user in the list because it already exists due to the last run.

Do you have any idea why this is happening or how I could fix it?

<img width="549" height="329" alt="Image" src="https://github.com/user-attachments/assets/8c25b1db-e53b-41b7-b74e-10666811b71f" />

```yaml
...
rootPassword:
  secret: &users nexus-users
  key: admin-password
config:
  enabled: true
  anonymous:
    enabled: true
    roles:
      - nx-anonymous
      - nx-metrics
  realms:
    enabled: true
    values:
      - NexusAuthenticatingRealm
      - DockerToken
      - NuGetApiKey
  blobStores:
    - name: &nuget-hosted-blob nuget-hosted
      type: s3
      bucketConfiguration:
        bucket:
          region: us-east-1
          name: '{{ .Values.nexus_bucket }}'
          prefix: nuget-hosted
          expiration: -1
    # - name: &nuget-proxy-blob nuget-proxy
    #   type: s3
    #   bucketConfiguration:
    #     bucket:
    #       region: us-east-1
    #       name: '{{ .Values.nexus_bucket }}'
    #       prefix: nuget-proxy
    #       expiration: 90
    - name: &pypi-hosted-blob pypi-hosted
      type: s3
      bucketConfiguration:
        bucket:
          region: us-east-1
          name: '{{ .Values.nexus_bucket }}'
          prefix: pypi-hosted
          expiration: -1
    - name: &apk-hosted-blob apk-hosted
      type: s3
      bucketConfiguration:
        bucket:
          region: us-east-1
          name: '{{ .Values.nexus_bucket }}'
          prefix: apk-hosted
          expiration: -1
  repos:
    - name: nuget-hosted
      format: nuget
      type: hosted
      online: false
      storage:
        blobStoreName: *nuget-hosted-blob
        strictContentTypeValidation: false
        writePolicy: allow
    # - name: nuget-proxy
    #   format: nuget
    #   type: proxy
    #   online: false
    #   storage:
    #     blobStoreName: *nuget-proxy-blob
    #     strictContentTypeValidation: false
    #     writePolicy: allow
    - name: pypi-hosted
      format: pypi
      type: hosted
      online: false
      storage:
        blobStoreName: *pypi-hosted-blob
        strictContentTypeValidation: false
        writePolicy: allow
    - name: apk-hosted
      format: raw
      type: hosted
      online: false
      storage:
        blobStoreName: *apk-hosted-blob
        strictContentTypeValidation: false
        writePolicy: allow
  users:
    - userId: apps
      firstName: APPS
      lastName: User
      emailAddress: apps@example.org
      status: active
      roles:
        - nx-admin
        - nx-anonymous
      password:
        secret: *users
        key: apps-password
    - userId: dev
      firstName: Dev
      lastName: User
      emailAddress: dev@example.org
      status: active
      roles:
        - nx-admin
        - nx-anonymous
      password:
        secret: *users
        key: dev-password
    - userId: dpm
      firstName: DPM
      lastName: User
      emailAddress: dpm@example.org
      status: active
      roles:
        - nx-admin
        - nx-anonymous
      password:
        secret: *users
        key: dpm-password
```
