### ISSUE TITLE
Consider moving configure.sh into a postStart lifecycle command

### ISSUE THREAD

**Issue by grumpydude** [stevehipwell/helm-charts#124]
Hi there,

One of the disadvantages of executing the configure.sh, given that it mostly executes in the background, as one of the commands is that if it fails, there is no feedback to helm for it to be able to recognise the failure. I've experimented with a post start lifecycle command (see below), and it works well. If the command fails, helm is able to recognise the failure and roll it back. Is it worth considering to replace both the `command` and `args` keys (plus removing the & from configure.sh) for the nexus3 container?

```
          lifecycle:
            postStart:
              exec:
                command:
                  - "sh"
                  - "-c"
                  - "${SONATYPE_DIR}/nexus/conf/configure.sh"
```

Thanks for this chart.

Regards,
