### ISSUE TITLE
Prune unnecessary blob stores and repos

### ISSUE THREAD

**Issue by grumpydude** [stevehipwell/helm-charts#130]
Is it worth adding functionality to allow for the removal of the default repos and blob stores? I thought about adding it as groovy to be run via the api, but perhaps it's better to let it be controlled by configure.sh

For example, one could add the following to the values.yaml:
```
  removeRepos:
    - name: nuget-group
    - name: nuget-hosted
    - name: nuget.org-proxy
```
And perhaps something like this to configure.sh:
```
  for json_file in "${base_dir}"/conf/*-repo-remove.json
  do
    if [ -f "${json_file}" ]
    then
      name="$(grep -Pio '(?<="name":)\s*\"[^"]+\"' "${json_file}" | xargs)"
      echo "Removing repo '${name}'..."

      status_code=$(curl -s -o /dev/null -w "%{http_code}" -X DELETE -H 'Content-Type: application/json' -u "${root_user}:${root_password}" "${nexus_host}/service/rest/v1/repositories/${name}")
      if [ "${status_code}" -ne 204 ]
      then
        echo "Could not remove repo." >&2
        exit 1
      fi

      echo "Repos removed."
    fi
  done
```
If this is something that you'd consider for this, do you have any preference on the way it's done?

**Comment by stevehipwell** [comment]
@grumpydude you can disable the built in repos by using the `online: false` key on the repo (see below); the code still looks correct although I haven't personally tested this since it was added.

```yaml
repos:
    - name: nuget-group
      online: false
    - name: nuget-hosted
      online: false
    - name: nuget.org-proxy
      online: false
```

For blob stores I don't want to allow the removal of these by an automated system due to the risk of a typo or yaml formatting issue causing data loss.
