### ISSUE TITLE
[sonarqube] chart templating issue

### ISSUE THREAD

**Issue by kuznetsov420** [stevehipwell/helm-charts#136]
Hello,
I've encountered a problem when tried to install Sonarqube helm-chart:
```
> helm install sonarqube stevehipwell/sonarqube -f sonarqube-values.yaml --namespace sonarqube --create-namespace --debug
install.go:172: [debug] Original chart version: ""
install.go:189: [debug] CHART PATH: /Users/admin/Library/Caches/helm/repository/sonarqube-1.0.0.tgz

Error: template: sonarqube/templates/deployment.yaml:122:61: executing "sonarqube/templates/deployment.yaml" at <include "sonarqube.postgresql.fullname" .>: error calling include: template: sonarqube/templates/_helpers.tpl:90:12: executing "sonarqube.postgresql.fullname" at <{{template "postgresql.fullname" $postgresContext}}>: template "postgresql.fullname" not defined
helm.go:81: [debug] template: sonarqube/templates/deployment.yaml:122:61: executing "sonarqube/templates/deployment.yaml" at <include "sonarqube.postgresql.fullname" .>: error calling include: template: sonarqube/templates/_helpers.tpl:90:12: executing "sonarqube.postgresql.fullname" at <{{template "postgresql.fullname" $postgresContext}}>: template "postgresql.fullname" not defined
```
My helm version:
```
> helm version
version.BuildInfo{Version:"v3.4.2", GitCommit:"23dd3af5e19a02d4f4baa5b2f242645a1a3af629", GitTreeState:"dirty", GoVersion:"go1.15.5"}
```

**Comment by stevehipwell** [comment]
Hi @kuznetsov420 could you give me the values you're using so I can check the solution I've got actually works for you?

**Comment by kuznetsov420** [comment]
I guess I've found typos: https://github.com/stevehipwell/helm-charts/pull/137

**Comment by kuznetsov420** [comment]
> Hi @kuznetsov420 could you give me the values you're using so I can check the solution I've got actually works for you?

here are my values btw:
<details>
  <summary>values.yaml</summary>

```
# Default values for sonarqube.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: sonarqube
  # Overrides the image tag whose default is {{ .Chart.AppVersion }}-community
  tag: ""
  pullPolicy: IfNotPresent
  pullSecrets: []

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext:
  fsGroup: 1000

securityContext:
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  runAsUser: 1000

livenessProbe:
  httpGet:
    path: /api/system/status
    port: http
  initialDelaySeconds: 60
  periodSeconds: 30
  failureThreshold: 10
  timeoutSeconds: 1

readinessProbe:
  httpGet:
    path: /api/system/status
    port: http
  initialDelaySeconds: 60
  periodSeconds: 30
  failureThreshold: 10
  timeoutSeconds: 1

service:
  type: ClusterIP
  annotations: {}
  port: 9000

ingress:
  enabled: true
  annotations: 
    certmanager.k8s.io/cluster-issuer: vault-prod
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 200m
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  hosts:
    - host: sonarqube.example.net
      http:
        paths: []
  tls:
   - secretName: sonarqube-tls
     hosts:
       - sonarqube.example.net

persistence:
  enabled: false
  annotations: {}
  # existingClaim: existing-pvc
  accessMode: ReadWriteOnce
  storageClass: standard
  size: 8Gi

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

caCerts:
  enabled: true
  secret: myown-rootca

envVars:
  jvmOptions: ""
  jvmAdditionalOptions: ""

env: []
  # - name: VARIABLE
  #   value: my-value

sonarProperties: {}

sonarSecretProperties:
  enabled: false
  secret:
  key:

installPlugins:
  enabled: false
  plugins: []
    # - name: my-plugin
    #   url: https://binaries.sonarsource.com/Distribution/my-plugin/my-plugin-1.0.0.jar
    #   copyToLib: false

## These settings are only required if you wish to use an existing postgresql instance
##
# psql:
  # host: postgresdb.local
  # port: 5432
  # database: sonarqube
  # username: sonarqube
  # password:
  #   secret: sonarqube-postgres
  #   key: password

## Configuration values for the postgresql dependency
## ref: https://artifacthub.io/packages/helm/bitnami/postgresql/10.2.0
##
postgresql:
  enabled: true
  postgresqlUsername: sonarqube
  postgresqlPassword: sonarqube
  postgresqlDatabase: sonarqube
```
</details>
