### ISSUE TITLE
Can't evaluate field paths in type interface

### ISSUE THREAD

**Issue by yuezhuangshi** [stevehipwell/helm-charts#242]
When using 2.8.1 plantuml charts, I have configuration as below  
```
ingress:
  enabled: true
  annotations: {}
  ingressClassName: "traefik"
  hosts: 
    - plantuml.local
```

After `helm install`, I got those errors, where should I define `paths`?  

`Error: template: plantuml/templates/NOTES.txt:4:12: executing "plantuml/templates/NOTES.txt" at <.paths>: can't evaluate field paths in type interface {}`
