### ISSUE TITLE
[nexus3] Add install plugins

### ISSUE THREAD

**Issue by kwangil-ha** [stevehipwell/helm-charts#265]
I want to install the composer plugin for my nexus3, without custom docker image. But It is not possible to install plugins with helm chart. Please add installing plugins like sonarqube helm chart.

**Comment by stevehipwell** [comment]
@kwangil-ha I'm going to look at writing for a solution for you so let's keep this issue open.

**Comment by EugenMayer** [comment]
Just in case this is interested, eventhough we are using https://sonatype.github.io/helm3-charts/ as the chart, we solved the same thing using an init container:

```yaml
    additionalVolumes:
      - name: nexus-deploy
        emptyDir: {}
    additionalVolumeMounts:
      - name: nexus-deploy
        mountPath: /opt/sonatype/nexus/deploy
...
    initContainers:
      - name: composer-download
        image: curlimages/curl
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh"]
        args:
          - -c
          - >-
              curl https://repo1.maven.org/maven2/org/sonatype/nexus/plugins/nexus-repository-composer/0.0.18/nexus-repository-composer-0.0.18-bundle.kar --output /deploy/nexus-repository-composer-0.0.18-bundle.kar
        volumeMounts:
          - name: nexus-deploy
            mountPath: /deploy
```

When you want to take the same route @stevehipwell  you would need to add support for additionalVolumes/addinitionMounts or just add a new PVC for deploy so the init container can mount it (maybe easier to do this).

Maybe this helps
