### ISSUE TITLE
[jira] Consider exposing tls/host for jira as common variables

### ISSUE THREAD

**Issue by EugenMayer** [stevehipwell/helm-charts#376]
Currently, host/tls env vars are only set, if the ingress is enabled.

In my case, we use Traefik, so we use CRDs to configure our own ingress route, thus ingress.enabled=false is used in the chart.

Due that ATL_TOMCAT_SECURE and the usuals are no longer set at the instance is not set.

One would need to add 

```yaml
env:
    - name: ATL_PROXY_PORT
      value: "443"
    - name: ATL_TOMCAT_SECURE
      value: "true"
    - name: ATL_TOMCAT_SCHEME
      value: "https"
    - name: ATL_PROXY_NAME
      value: "myjira.tld"
```

I understand that this is perfectly possible - i would though suggest to expose host/tls as common values, not specific to ingress.

Something like `hostname` and `enabledTls` on the topLevel. Then use those to populate ATL_PROXY_PORT/ATL_TOMCAT_SECURE/ATL_TOMCAT_SCHEME/ATL_PROXY_NAME

Any ideas if that makes sense for you?
