### ISSUE TITLE
tigera-operator: failed to list *v1beta1.PodSecurityPolicy:

### ISSUE THREAD

**Issue by gclawes** [stevehipwell/helm-charts#403]
As of v2.1.0 helm chart, `tigera-operator` is unable to list `*v1beta1.PodSecurityPolicy`:

```
{"level":"info","ts":1644161221.9355175,"logger":"status_manager.calico","msg":"Status manager is not ready to report component statuses."}
E0206 15:27:06.207604       1 reflector.go:138] pkg/mod/k8s.io/client-go@v0.21.7/tools/cache/reflector.go:167: Failed to watch *v1beta1.PodSecurityPolicy: failed to list *v1beta1.PodSecurityPolicy: podsecuritypolicies.policy is forbidden: User "system:serviceaccount:tigera-operator:tigera-operator" cannot list resource "podsecuritypolicies" in API group "policy" at the cluster scope
```

This prevents the operator from deploying calico.  This occurs on both clean installs with the provided helm chart and CRDs, as well as on upgrade from `2.0.1` with the provided CRDs applied with `kubectl apply` pre-upgrade.

The following `.Values.rbac.customRules` fix this:
```
rbac:
  customRules:
    - apiGroups:
        - policy
      resources:
        - podsecuritypolicies
      verbs:
        - create
        - get
        - list
        - update
        - delete
        - watch
```

These should probably be integrated into the default `policy` rule here: https://github.com/stevehipwell/helm-charts/blob/7e786ab8a57251d9d26e3df2292cb336ed8845d0/charts/tigera-operator/templates/clusterrole.yaml#L152-L162
