### ISSUE TITLE
Secrets and extravolumes for fluentd-aggregator

### ISSUE THREAD

**Issue by PushRom** [stevehipwell/helm-charts#414]
Hello!
It would be great to add the creation of secrets and extravolumes to the fluentd-aggregator chart. To mount certificates from secrets, for example.

**Comment by stevehipwell** [comment]
@PushRom I'd be happy to add extra volumes to the chart, it's actually already coded and just waiting for a chart minor release. I think all the secret mounts other than volume are present. I won't enable the creation of secrets through the chart, this isn't a good pattern as the secret values end up in the Helm state and lifecycling secrets with Helm doesn't make sense. I'd recommend always maintaining external secrets external to the chart.

**Comment by PushRom** [comment]
Ok. Let's wait for the release

**Comment by stevehipwell** [comment]
@PushRom even with the coming `extraVolumeMounts` I'd recommend binding your secrets to `env` as demonstrated below; you can then use them directly in your [Fluentd config](https://docs.fluentd.org/quickstart/faq#how-can-i-use-environment-variables-to-configure-parameters-dynamically). The added benefit of this is that it works in the current chart version (I use it extensively).

```yaml
env:
  - name: SECRET_USERNAME
    valueFrom:
        secretKeyRef:
          name: mysecret
          key: username
    - name: SECRET_PASSWORD
      valueFrom:
        secretKeyRef:
          name: mysecret
          key: password
```
