### ISSUE TITLE
adding s3 blobstore

### ISSUE THREAD

**Issue by mkuzniarski** [stevehipwell/helm-charts#416]
Hi,

Are you planning to add s3 blobstore functionality for nexus3?
 
configuration would look something like: 

  BlobStores:
      - name: s3-blobstore
         type: s3
         bucketName: 
         region:
         accessKeyID:
         secretAccessKey:

and so on

**Comment by stevehipwell** [comment]
@mkuzniarski S3 blob stores are already supported, the config should align to the blobstore API.

**Comment by mkuzniarski** [comment]
thanks, I'll give it a try.
for now I'm struggling with:

Exec lifecycle hook ([/bin/sh -c ${SONATYPE_DIR}/nexus/conf/configure.sh > /proc/1/fd/1 2>/proc/1/fd/2]) for Container "nexus3" in Pod "nexus-nexus3-794bcd4dd6-5msn9_nexus(637c836a-2a1f-42a8-a095-52ecaaa0bbc6)" failed - error: command '/bin/sh -c ${SONATYPE_DIR}/nexus/conf/configure.sh > /proc/1/fd/1 2>/proc/1/fd/2' exited with 1: , message: ""

it happens when I'm trying to pass any configuration with:
config:
  enabled: true

**Comment by stevehipwell** [comment]
@mkuzniarski what's the full config you're using?

**Comment by mkuzniarski** [comment]
here's my full config (replaced some data with '***' )
the 'nexus-ad' secret is already created as well as the nexus pvc


```
image:
  repository: sonatype/nexus3
  # Overrides the image tag whose default is {{ .Chart.AppVersion }}
  tag: ""
  pullPolicy: IfNotPresent
  pullSecrets: []

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podLabels: {}
podAnnotations: {}

podSecurityContext:
  fsGroup: 200

securityContext:
  runAsGroup: 200
  runAsUser: 200

priorityClassName: ""

livenessProbe:
  httpGet:
    path: /service/rest/v1/status
    port: http
  initialDelaySeconds: 60
  periodSeconds: 30
  failureThreshold: 10
  timeoutSeconds: 1

readinessProbe:
  httpGet:
    path: /service/rest/v1/status
    port: http
  initialDelaySeconds: 60
  periodSeconds: 30
  failureThreshold: 10
  timeoutSeconds: 1

service:
  type: ClusterIP
  annotations: {}
  port: 8081
  additionalPorts: []
  #   - port: 8082
  #     name: docker-group
  #     containerPort: 8082
  #     host: nexus-docker.local
  #   - port: 8083
  #     name: docker-hosted
  #     containerPort: 8083
  #     host: nexus-docker-hosted.local

metrics:
  enabled: false
  serviceMonitor:
    enabled: false
    additionalLabels: {}
    #   myLabel: myValue
    interval: 1m

ingress:
  enabled: false
  annotations: {}
  ingressClassName: ""
  hosts: []
  #   - nexus.local
  tls: []
  #   - hosts:
  #       - nexus.local
  #       - nexus-docker.local
  #       - nexus-docker-hosted.local
  #     secretName: nexus-local-tls

persistence:
  enabled: true
  annotations: {}
  existingClaim: nexus
  storageClassName: aws-efs
  accessMode: ReadWriteOnce
  size: 8Gi

extraVolumeMounts: []

resources: {}
# We usually recommend not to specify default resources and to leave this as a conscious
# choice for the user. This also increases chances charts run on environments with little
# resources, such as Minikube. If you do want to specify resources, uncomment the following
# lines, adjust them as necessary, and remove the curly braces after 'resources:'.
#   limits:
#     cpu: 100m
#     memory: 128Mi
#   requests:
#     cpu: 100m
#     memory: 128Mi

extraInitContainers: []

extraVolumes: []

nodeSelector: {}

tolerations: []

affinity: {}

caCerts:
  enabled: false
  secret:

envVars:
  jvmMinHeapSize: 1024m
  jvmMaxHeapSize: 1024m
  jvmAdditionalMemoryOptions: "-XX:MaxDirectMemorySize=2048m"
  jvmAdditionalOptions: ""

env: []
#   - name: VARIABLE
#     value: my-value

logback:
  maxHistory: 30

properties:
  - nexus.scripts.allowCreation=true
  # - nexus.golang.hosted=true

config:
  enabled: true
  # rootPassword:
  #   secret: root-secret-name
  #   key: password
  anonymous:
    enabled: true
  realms:
    enabled: false
    values: 
      - NexusAuthenticatingRealm
      - NexusAuthorizingRealm
      - LdapRealm
      - NpmToken
      - NuGetApiKey
  ldap:
    enabled: false
    name: cwg
    protocol: ldaps
    useTrustStore: true
    connectionTimeoutSeconds: 30
    connectionRetryDelaySeconds: 300
    maxIncidentsCount: 3
    host: 10.130.1.31
    port: 389
    authScheme: simple
    authUsername: ****
    authPassword: 
      secret: nexus-ad
      key: adpassword
    authRealm: 
    searchBase:
    userBaseDn: ****
    userSubtree: true
    userObjectClass: user
    userLdapFilter:
    userIdAttribute: sAMAccountName
    userRealNameAttribute: cn
    userEmailAddressAttribute: mail
    userPasswordAttribute:
    ldapGroupsAsRoles: false
    groupType: dynamic
    userMemberOfAttribute: memberOf
    groupBaseDn:
    groupSubtree: false
    groupObjectClass:
    groupIdAttribute:
    groupMemberAttribute:
    groupMemberFormat:
  blobStores: []
    # - name: s3-blobstore
    #   type: s3
    #   bucketConfiguration:
    #     bucket": 
    #       region:  
    #       name":
    #     bucketSecurity:
    #       accessKeyId:
    #       secretAccessKey:
  cleanup: []
  #   - name: ExampleCleanup
  #     notes: "Cleanup content that hasn't been updated in 14 days downloaded in 28 days."
  #     format: ALL_FORMATS
  #     mode: delete
  #     criteria:
  #       isPrerelease:
  #       lastBlobUpdated: "1209600"
  #       lastDownloaded: "2419200"
  #       regex:
  repoCredentials:
    enabled: false
    secret:
  repos: []
  #   - name: test-repo
  #     type: raw-hosted
  #     online: true
  #     attributes:
  #       storage:
  #         blobStoreName: default
  #         strictContentTypeValidation: false
  #         writePolicy: ALLOW
  #       cleanup:
  #         policyName:
  #           - ExampleCleanup
  roles: []
  #   - id: nexus-administrators
  #     source: default
  #     name: nexus-administrators
  #     description: LDAP Administrator Role
  #     privileges: []
  #     roles:
  #       - nx-admin
  tasks: []
  #   - name: "Cleanup service"
  #     typeId: repository.cleanup
  #     crontab: "0 0 0 * * ?"
  #   - name: "Docker cleanup uploads"
  #     typeId: repository.docker.upload-purge
  #     crontab: "0 0 0 * * ?"
  #     attributes:
  #       age: "24"
  #   - name: "Docker cleanup artifacts"
  #     typeId: repository.docker.gc
  #     crontab: "0 0 1 * * ?"
  #     attributes:
  #       repositoryName: "*"
  #   - name: "Cleanup blob store"
  #     typeId: blobstore.compact
  #     crontab: "0 0 2 * * ?"
  #     attributes:
  #       blobStoreName: "default"
```
