### ISSUE TITLE
SonarQube chart: %!s(float64=5432) port error

### ISSUE THREAD

**Issue by dervos** [stevehipwell/helm-charts#446]
The recent change in sonarqube-4.4.1 resulted in a startup error caused by a malformed jdbc database url.
```
INFO  web[][o.sonar.db.Database] Create JDBC data source for jdbc:postgresql://xxx.xxx.xxx.xxx:%!s(float64=5432)/xxx
WARN  web[][o.p.u.PGPropertyUtil] JDBC URL invalid port number: %!s(float64=5432)
```

values.yaml
```yaml
psql:
  enable: true
  host: "xxxx"
  port: 5432
  database: xxx
  username: xxx
  password:
    secret: xxx
    key: xxx
```
Enclosing the port number resolved the issue.
```yaml
psql:
  port: "5432"
```
After some research, this could be an issue with https://github.com/kubernetes-sigs/yaml/issues/45. So this is probably related to my delivery solution. Thoughts?
