### ISSUE TITLE
Updating for 5.1.0 -> 5.1.1 or 5.1.1 -> 5.1.2 fails on stateful set

### ISSUE THREAD

**Issue by EugenMayer** [stevehipwell/helm-charts#497]
```
 cannot patch "jira" with kind StatefulSet: StatefulSet.apps "jira" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', 'updateStrategy', 'persistentVolumeClaimRetentionPolicy' and 'minReadySeconds' are forbidden
```

I did not change anything in my values, just updated the helm chart.

Is an update for you working when using stateful sets?

**Comment by EugenMayer** [comment]
I had to entirely remove the stateful set (manually) and then it has been recreated - but this cannot be the plan, right?
looking at your changes from 5.1.0 to 5.1.1 nothing really changed, so I am confused

**Comment by stevehipwell** [comment]
@EugenMayer there have been no template code changes since `v5.0.0` so maybe there is something in the `StatefulSet` template that was copied from the `Deployment` template which isn't working correctly in this context?

I've just run a test on kind and I can upgrade from v5.0.0 to v5.1.1.

**Comment by EugenMayer** [comment]
Thank you for looking in that one. I cannot really explain it. 

I will wait for the next update - this one i manually removed the stateful set and then re-applied, so it was created from scratch and should no match what ever is in the helm chart 100% - i guess when the next update comes, i will see if this happens again, and if it does, there might be a good argument that there is an actual issue

So IMHO we could close this issue and i would open a new one if needed (with the next update) referencing this one. 

What do you think?

**Comment by EugenMayer** [comment]
Today i tried upgrading to 5.1.2 and ended up in the very same situation above:

```
│ Error: cannot patch "jira" with kind StatefulSet: StatefulSet.apps "jira" is invalid: spec: Forbidden: updates to statefulset spec for fields other than 'replicas', 'template', 'updateStrategy', 'persistentVolumeClaimRetentionPolicy' and 'minReadySeconds' are forbidden
```

Since i removed the stateful set the last time and it had been recreated automatically, i assume it was cleanly created and was for sure not manually tempered with

Those are the values i deploy with

```yaml
ingress:
  enabled: false
fullnameOverride: "jira"
serviceAccount:
  create: false
persistence:
  enabled: true
  storageClass: longhorn
  size: ${disk_size}
envVars:
  jvmMinHeapSize: 2048M
  jvmMaxHeapSize: 4096M
  jvmAdditionalMemoryOptions: "-XX:+UseG1GC"
  jvmAdditionalOptions: "-XX:ReservedCodeCacheSize=1024m"
env:
  - name: ATL_PROXY_PORT
    value: "443"
  - name: ATL_TOMCAT_SECURE
    value: "true"
  - name: ATL_TOMCAT_SCHEME
    value: "https"
  - name: ATL_PROXY_NAME
    value: "${hostname}"
psql:
  password:
    secret: ${pg_secret_name}
    key: ${pg_secret_key}
  host: ${pg_host}
  port: ${pg_port}
  database: ${db_name}
  username: ${pg_username}
```

All template variables are feeded via tf, so do not wonder. That is basically what i end to be using as values.yaml.

Could those env vars be a problem in the stateful set (that's my smell)? Just to be clear, the tf values have not been changed, so all values ar ethe same - it is even diffed, so i can tell for sure.
