### ISSUE TITLE
[nexus3] admin.password created on every startup causing start to fail

### ISSUE THREAD

**Issue by timdeluxe** [stevehipwell/helm-charts#596]
On my setup the "admin.password" is generated on every startup with a new generated (random) entry. This file is for initial setups, but the password is already changed and works on the UI (before the restart). If i remove the admin.password file the startup continues and also if i set the content of admin.password to the changed one the startup also continues.
But this means manual activity at every startup, which is annoying.
There must be some flag somewhere, which tells nexus to stop that, but i can't figure out what/where that is.

My values related to that (the secret contains the desired password):
```
      config:
        enabled: true
        rootPassword:
          secret: nexus-root-password
          key: nexus-root-password
```
Has anybody an idea?

**Comment by stevehipwell** [comment]
@timdeluxe I'd need to know which chart version you were using and the rest of the values. Can you also confirm that you're populating the Secret and it's that password which is being applied?

**Comment by timdeluxe** [comment]
@stevehipwell 
Chart version 4.18.0.
Yes, the secret is populated and that is the password which is tried to be applied in your configure script, however it can't authenticate to the REST API because it reads the password from admin.password file to authenticate against the REST API, which is wrong.

All values (a bit redacted):
```

                priorityClassName: ""
                ingress:
                  enabled: true
                  hosts:
                     - artifacts-nexus.example.com
                  tls:
                     - hosts:
                         - artifacts-nexus.example.com
                       secretName: artifacts-nexus-certificate
                persistence:
                  enabled: true
                  storageClass: kubernetes-policy
                  size: 300Gi
                extraVolumes:
                  - name: migration-nfs
                    nfs:
                     server: 10.2.3.4
                     path: /artifacts-migration
                extraVolumeMounts:
                  - name: migration-nfs
                    mountPath: /migration-nfs
                resources:
                  limits:
                    cpu: 4
                env:
                    - name: NEXUS_DATASTORE_NEXUS_JDBCURL
                      value: "jdbc:postgresql://platformdb-artifacts-db-pooler:5432/nexus"
                    - name: NEXUS_DATASTORE_NEXUS_USERNAME
                      valueFrom:
                        secretKeyRef:
                          name: nexus.platformdb-artifacts-db.credentials.postgresql.acid.zalan.do
                          key: username
                    - name: NEXUS_DATASTORE_NEXUS_PASSWORD
                      valueFrom:
                        secretKeyRef:
                          name: nexus.platformdb-artifacts-db.credentials.postgresql.acid.zalan.do
                          key: password
                properties:
                  - nexus.scripts.allowCreation=true
                  - nexus.datastore.enabled=true
                  - nexus.datastore.nexus.name=nexus
                  - nexus.datastore.nexus.type=jdbc
                plugins: []
                config:
                  enabled: true
                  rootPassword:
                    secret: nexus-root-password
                    key: nexus-root-password
```

**Comment by timdeluxe** [comment]
Found a workaround:
```
          - name: NEXUS_SECURITY_INITIAL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: nexus-root-password
                key: nexus-root-password
```
In the "env:" block of the values.
Found that here:
https://github.com/sonatype/nexus-public/blob/c43280a44a1c9c3e00a23e21ed4e0ac6ab3046f1/components/nexus-security/src/main/java/org/sonatype/nexus/security/config/StaticSecurityConfigurationSource.groovy#L60
At least now the startup works without manual intervention.
