### ISSUE TITLE
[thanos] allow setting objConfig as an object or string

### ISSUE THREAD

**Issue by onedr0p** [stevehipwell/helm-charts#646]
Hi 👋 Thanks for maintaining this chart. I am thinking about migrating over to this chart from the bitnami chart because it looks like you have a working thanos receiver where Bitnami does not.

https://github.com/bitnami/charts/issues/14248

Having the ability to set the objstore as an object would allow me to patch in the config.

For example:

```yaml
    objstoreConfig:
      type: s3
      config:
        insecure: true
```

and then in the Flux HelmRelease I can patch in the values from existing secrets or configmaps

```yaml
  valuesFrom:
    - targetPath: objstoreConfig.config.bucket
      kind: ConfigMap
      name: thanos-bucket-v1
      valuesKey: BUCKET_NAME
    - targetPath: objstoreConfig.config.endpoint
      kind: ConfigMap
      name: thanos-bucket-v1
      valuesKey: BUCKET_HOST
    - targetPath: objstoreConfig.config.region
      kind: ConfigMap
      name: thanos-bucket-v1
      valuesKey: BUCKET_REGION
    - targetPath: objstoreConfig.config.access_key
      kind: Secret
      name: thanos-bucket-v1
      valuesKey: AWS_ACCESS_KEY_ID
    - targetPath: objstoreConfig.config.secret_key
      kind: Secret
      name: thanos-bucket-v1
      valuesKey: AWS_SECRET_ACCESS_KEY
```

For what it's worth Bitnami allows this value to be a string or object in their templates

https://github.com/bitnami/charts/blob/main/bitnami/thanos/templates/objstore-secret.yaml

Thanks!
