### ISSUE TITLE
[thanos] no external labels configured for receive

### ISSUE THREAD

**Issue by onedr0p** [stevehipwell/helm-charts#651]
Hi Steve! 

It appears the label for `receive_replica` is not passed to the receive router? Should this label be automatically added or should it be added via `extraArgs` on the router?

Values:

```yaml
additionalReplicaLabels: ["__replica__"]
objstoreConfig:
  key: objstore.yml
  value:
    type: s3
    config:
      insecure: true
compact:
  enabled: true
  extraArgs:
    - --compact.concurrency=4
    - --delete-delay=30m
    - --retention.resolution-1h=14d
    - --retention.resolution-5m=14d
    - --retention.resolution-raw=14d
  persistence:
    enabled: true
    storageClass: local-path
    size: 20Gi
query:
  enabled: true
  replicas: 3
queryFrontend:
  enabled: true
  replicas: 3
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/whitelist-source-range: |
        10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
      hajimari.io/enable: "false"
    hosts:
      - &host thanos-query-frontend.devbu.io
    tls:
      - hosts:
          - *host
receive:
  enabled: true
  replicationFactor: 3
  retention: 12h
  router:
    replicas: 3
  ingestor:
    replicas: 3
    extraArgs:
      - --tsdb.wal-compression
      - --receive.hashrings-algorithm=ketama
    persistence:
      enabled: true
      storageClass: local-path
      size: 20Gi
storeGateway:
  replicas: 3
  persistence:
    enabled: true
    storageClass: local-path
    size: 20Gi
rule:
  enabled: true
  replicas: 3
  extraArgs:
    - --web.prefix-header=X-Forwarded-Prefix
  alertmanagersConfig:
    value: |
      alertmanagers: ["http://kube-prometheus-stack-alertmanager.monitoring.svc.cluster.local:9093"]
  rules:
    value: |-
      groups:
        - name: PrometheusWatcher
          rules:
            - alert: PrometheusDown
              annotations:
                summary: A Prometheus has disappeared from Prometheus target discovery
              expr: absent(up{job="kube-prometheus-stack-prometheus"})
              for: 10m
              labels:
                severity: critical
  persistence:
    enabled: true
    storageClass: local-path
    size: 20Gi
serviceMonitor:
  enabled: true

```

Logs:

```
level=error ts=2023-03-28T15:13:28.14420834Z caller=main.go:135 err="no external labels configured for receive, uniquely identifying external labels must be configured (ideally with `receive_` prefix); see https://thanos.io/tip/thanos/storage.md#external-labels for details.\nmain.registerReceive.func1\n\t/app/cmd/thanos/receive.go:71\nmain.main\n\t/app/cmd/thanos/main.go:133\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:250\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1594\npreparing receive command failed\nmain.main\n\t/app/cmd/thanos/main.go:135\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:250\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1594"
```

Rendered args for receive router:

```yaml
      - args:
        - receive
        - --log.level=info
        - --log.format=logfmt
        - --grpc-address=0.0.0.0:10901
        - --http-address=0.0.0.0:10902
        - --remote-write.address=0.0.0.0:19291
        - --receive.hashrings-file=/var/lib/thanos-receive/hashrings.json
        - --receive.replication-factor=3
```

**Comment by onedr0p** [comment]
I also noticed on the receiver ingestor that there is a uncommented quote:

```yaml
      - args:
        - receive
        - --log.level=info
        - --log.format=logfmt
        - --grpc-address=0.0.0.0:10901
        - --http-address=0.0.0.0:10902
        - --remote-write.address=0.0.0.0:19291
        - --objstore.config-file=/etc/thanos/objstore.yaml
        - --tsdb.path=/var/thanos/receive
        - --tsdb.retention=12h
        - --label=receive_replica="$(NAME) # Should this quote be terminated?
        - --receive.local-endpoint=$(NAME).thanos-receive-ingestor.monitoring-headless.svc.cluster.local:10901
        - --tsdb.wal-compression
        - --receive.hashrings-algorithm=ketama
```

**Comment by stevehipwell** [comment]
@onedr0p could you try again but move your hashring arg to the router?

I also can't replicate your missing quote?

**Comment by onedr0p** [comment]
I have updated the values to point the hashring algorithm on the router, however I still have that same error about `no external labels configured`

Updated values:

```yaml
    additionalReplicaLabels: ["__replica__"]
    objstoreConfig:
      key: objstore.yml
      value:
        type: s3
        config:
          insecure: true
    compact:
      enabled: true
      extraArgs:
        - --compact.concurrency=4
        - --delete-delay=30m
        - --retention.resolution-1h=14d
        - --retention.resolution-5m=14d
        - --retention.resolution-raw=14d
      persistence:
        enabled: true
        storageClass: local-path
        size: 20Gi
    query:
      enabled: true
      replicas: 3
    queryFrontend:
      enabled: true
      replicas: 3
      ingress:
        enabled: true
        ingressClassName: nginx
        annotations:
          nginx.ingress.kubernetes.io/whitelist-source-range: |
            10.0.0.0/8,172.16.0.0/12,192.168.0.0/16
          hajimari.io/enable: "false"
        hosts:
          - &host thanos-query-frontend.devbu.io
        tls:
          - hosts:
              - *host
    receive:
      enabled: true
      replicationFactor: 3
      retention: 12h
      router:
        replicas: 3
        extraArgs:
          - --receive.hashrings-algorithm=ketama
      ingestor:
        replicas: 3
        extraArgs:
          - --tsdb.wal-compression
        persistence:
          enabled: true
          storageClass: local-path
          size: 20Gi
    storeGateway:
      replicas: 3
      persistence:
        enabled: true
        storageClass: local-path
        size: 20Gi
    rule:
      enabled: true
      replicas: 3
      extraArgs:
        - --web.prefix-header=X-Forwarded-Prefix
      alertmanagersConfig:
        value: |-
          alertmanagers:
            - api_version: v2
              scheme: http
              timeout: 30s
              static_configs:
                - kube-prometheus-stack-alertmanager.monitoring.svc.cluster.local:9093
      rules:
        value: |-
          groups:
            - name: PrometheusWatcher
              rules:
                - alert: PrometheusDown
                  annotations:
                    summary: A Prometheus has disappeared from Prometheus target discovery
                  expr: absent(up{job="kube-prometheus-stack-prometheus"})
                  for: 10m
                  labels:
                    severity: critical
      persistence:
        enabled: true
        storageClass: local-path
        size: 20Gi
    serviceMonitor:
      enabled: true
```

**Comment by onedr0p** [comment]
However it doesn't appear to be mounted correctly...

```yaml
        volumeMounts:
        - mountPath: /etc/thanos/hashrings.json
          name: hashrings-config
          readOnly: true
          subPath: hashrings.json
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 65534
        runAsUser: 65534
      serviceAccount: thanos-receive-router
      serviceAccountName: thanos-receive-router
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: thanos-receive-router-hashrings
        name: hashrings-config
```
