### ISSUE TITLE
Possible Ingress issue with Jira Helm Chart on Gadgets

### ISSUE THREAD

**Issue by ikappas** [stevehipwell/helm-charts#73]
After installing the Jira helm chart on my lab I get `gadget.common.error.500` and `__MSG_gadget.project.title__`  displayed at the system dashboard along with a warning in Administration > System > Troubleshooting and support tools about a problem with gadget feed URL.

![image](https://user-images.githubusercontent.com/7887523/89887157-79225980-dbd6-11ea-9305-93bc9c58b52b.png)

The configuration overrides used are: 
```yaml
---
  caCerts:
    enabled: "true"
    secret: "jira-custom-ca"
  envVars:
    jvmAdditionalOptions: "-Dhttp.nonProxyHosts=\"*.docker.internal|localhost\" -Dhttps.nonProxyHosts=\"*.docker.internal|localhost\""
  ingress: 
    annotations: 
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/proxy-body-size: "0"
      nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
      nginx.ingress.kubernetes.io/proxy-send-timeout: "600"
      nginx.ingress.kubernetes.io/secure-backends: "true"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
    enabled: "true"
    hosts: 
      - "jira.docker.internal"
    tls:
      - secretName: "tls-docker-internal"
        hosts:
         - "jira.docker.internal"
  persistence: 
    enabled: "true"
    existingClaim: "pvc-jira-data"
  postgresql: 
    enabled: "true"
    persistence: 
      enabled: "true"
      existingClaim: "pvc-jira-database"

```

Thank you in advance for your assistance!

**Comment by stevehipwell** [comment]
@ikappas have you checked back at the status? Jira usually reports this issue as well as liked applications, if you have any, after it has been restarted.

**Comment by ikappas** [comment]
@stevehipwell I have restarted the application many times and the issue persists

**Comment by stevehipwell** [comment]
@ikappas I'm pretty confident that there isn't a chart ingress issue as I've been running a version of this chart using https and a self-signed cert for over a year with no issues. I suggest that you look at the non proxy host arguments that you're setting on the JVM and your ingress annotations as that's something that I've not seen used. Other than that I'd suggest running Jira over http first as gadgets can be fussy with https connections and self signed certificates.

**Comment by stevehipwell** [comment]
>@stevehipwell I have restarted the application many times and the issue persists

@ikappas I didn't say to re-start, I said to check back at the status. You might also want to check what's happening in your browser dev tools.

**Comment by ikappas** [comment]
@stevehipwell Thanks for answer. Do you think you can share a basic set of values to set the ingress with self signed certificate?

**Comment by stevehipwell** [comment]
@ikappas the ingress settings on our primary chart is as follows, but please note that the ingress controller has been configured centrally and tested with a number of services. I'd still recommend you starting first with http.

```yaml
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: my-ingress-class
    cert-manager.io/cluster-issuer: my-issuer
  hosts:
    - jira.my-domain.dev
  tls:
    - secretName: jira-cert
      hosts:
        - jira.my-domain.dev
```
