### ISSUE TITLE
[thanos] support prometheus sidecar method of deployment

### ISSUE THREAD

**Issue by onedr0p** [stevehipwell/helm-charts#912]
Hi 👋🏼 

It would be awesome if this Thanos chart could support the [prometheus-sidecar](https://thanos.io/tip/components/sidecar.md/#sidecar) method. I am trying to move away from Bitnami and you do an excellent job here. 🎉 

For what it's worth, in the bitnami chart it looks like this:

```yaml
    query:
      dnsDiscovery:
        sidecarsService: kube-prometheus-stack-thanos-discovery
        sidecarsNamespace: observability
```

And the templated values...

https://github.com/bitnami/charts/blob/73c549c15fcf5c4572e14746993ecdd92242b3ac/bitnami/thanos/templates/query/deployment.yaml#L119-L121

**Comment by stevehipwell** [comment]
@onedr0p are you asking how to configure Thanos query to include sidecars? If so the following configuration should make Thanos work correctly (this is how we use Thanos).

```yaml
additionalReplicaLabels:
  - prometheus_replica

additionalEndpoints:
  - dnssrv+_grpc._tcp.kube-prometheus-stack-thanos-discovery.observability.svc.cluster.local
```
