### ISSUE TITLE
thanos-recever-router ingress creation issue

### ISSUE THREAD

**Issue by berjanb** [stevehipwell/helm-charts#937]
Hello 👋🏼

I am installing thanos helm-chart enabling receive mode,
After evcerything is conciled, ingress missing remote_write endpoint which is in thanos-recever-router service with port: 19291

Ingress path has only one
```
  rules:
    - host: thanos-ingest.mydomain.mn
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: thanos-receive-router
                port:
                  number: 10902
```
also values.yaml has no other option to add following paths as addiotnally 

```
          - path: /api/v1/receive
            pathType: Prefix
            backend:
              service:
                name: thanos-receive-router
                port:
                  number: 19291
```

it would be nice if 3 ports and paths enabled by default for the ingress
