### ISSUE TITLE
Missing Permissions for ippools in tigera-operator ClusterRole v2.10.0

### ISSUE THREAD

**Issue by aydosman** [stevehipwell/helm-charts#971]
I encountered an issue with the tigera-operator when upgrading from 2.9.3>2.10.0. The ClusterRole for the tigera-operator does not include the necessary permissions to list ippools in the crd.projectcalico.org API group. This results in the following error on the tiger-operator pod:

```bash
W0604 11:47:15.528475 1 reflector.go:535] pkg/mod/k8s.io/client-go@v0.28.9/tools/cache/reflector.go:229: failed to list *v1.IPPool: ippools.crd.projectcalico.org is forbidden: User "system:serviceaccount:tigera-operator:tigera-operator" cannot list resource "ippools" in API group "crd.projectcalico.org" at the cluster scope
E0604 11:47:15.528508 1 reflector.go:147] pkg/mod/k8s.io/client-go@v0.28.9/tools/cache/reflector.go:229: Failed to watch *v1.IPPool: failed to list *v1.IPPool: ippools.crd.projectcalico.org is forbidden: User "system:serviceaccount:tigera-operator:tigera-operator" cannot list resource "ippools" in API group "crd.projectcalico.org" at the cluster scope
```

After a short time the pod crash loops. 
I've verified I've properly updated crds.

The issue can be resolved by adding the necessary permissions to the ClusterRole for tigera-operator. The following block needs to be added to the ClusterRole definition:

```yaml
- verbs:
    - get
    - list
    - watch
  apiGroups:
    - crd.projectcalico.org
  resources:
    - ippools
```

Here is the updated ClusterRole definition with the necessary permissions added:

```yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tigera-operator
rules:
  - verbs:
      - create
      - get
      - list
      - update
      - delete
      - watch
    apiGroups:
      - ''
    resources:
      - namespaces
      - pods
      - podtemplates
      - services
      - endpoints
      - events
      - configmaps
      - secrets
      - serviceaccounts
  - verbs:
      - list
      - get
      - watch
    apiGroups:
      - ''
    resources:
      - resourcequotas
  - verbs:
      - create
      - get
      - list
      - update
      - delete
      - watch
    apiGroups:
      - ''
    resources:
      - resourcequotas
    resourceNames:
      - calico-critical-pods
      - tigera-critical-pods
  - verbs:
      - get
      - patch
      - list
      - watch
    apiGroups:
      - ''
    resources:
      - nodes
  - verbs:
      - create
      - get
      - list
      - update
      - delete
      - watch
      - bind
      - escalate
    apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - clusterroles
      - clusterrolebindings
      - rolebindings
      - roles
  - verbs:
      - create
      - get
      - list
      - patch
      - update
      - delete
      - watch
    apiGroups:
      - apps
    resources:
      - deployments
      - daemonsets
      - statefulsets
  - verbs:
      - update
    apiGroups:
      - apps
    resources:
      - deployments/finalizers
    resourceNames:
      - tigera-operator
  - verbs:
      - get
      - list
      - update
      - patch
      - watch
    apiGroups:
      - operator.tigera.io
    resources:
      - apiservers/finalizers
      - installations
      - installations/status
      - installations/finalizers
      - tigerastatuses
      - tigerastatuses/status
      - tigerastatuses/finalizers
      - apiservers
      - apiservers/status
      - imagesets
  - verbs:
      - create
      - delete
    apiGroups:
      - operator.tigera.io
    resources:
      - tigerastatuses
  - verbs:
      - delete
    apiGroups:
      - operator.tigera.io
    resources:
      - installations
      - apiservers
  - verbs:
      - create
      - update
      - delete
      - get
      - list
      - watch
    apiGroups:
      - networking.k8s.io
    resources:
      - networkpolicies
  - verbs:
      - create
      - patch
      - list
      - get
      - watch
    apiGroups:
      - crd.projectcalico.org
    resources:
      - felixconfigurations
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - crd.projectcalico.org
    resources:
      - kubecontrollersconfigurations
      - bgpconfigurations
  - verbs:
      - create
      - update
      - delete
      - patch
      - get
      - list
      - watch
    apiGroups:
      - projectcalico.org
    resources:
      - ippools
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - crd.projectcalico.org
    resources:
      - ippools
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - projectcalico.org
    resources:
      - ipamconfigurations
  - verbs:
      - create
      - get
      - list
      - update
      - delete
      - watch
    apiGroups:
      - scheduling.k8s.io
    resources:
      - priorityclasses
  - verbs:
      - create
      - get
      - list
      - update
      - delete
      - watch
    apiGroups:
      - policy
    resources:
      - poddisruptionbudgets
  - verbs:
      - list
      - watch
      - create
      - update
    apiGroups:
      - apiregistration.k8s.io
    resources:
      - apiservices
  - verbs:
      - create
      - get
      - list
      - update
      - delete
      - watch
    apiGroups:
      - coordination.k8s.io
    resources:
      - leases
  - verbs:
      - list
      - watch
      - update
      - get
      - create
      - delete
    apiGroups:
      - storage.k8s.io
    resources:
      - csidrivers
  - verbs:
      - list
      - watch
    apiGroups:
      - certificates.k8s.io
    resources:
      - certificatesigningrequests
```

I manually made the change and all seems well _post_ change. Let me know if you need any further information.
